### PR TITLE
fix: made most props optional for TransformControls

### LINKED ISSUE #444: <TransformControls /> component does not work in typescript after upgraded drei from 2.1.1 to 5.0.0
- `three` version:
- `@react-three/fiber` version: 6.0.0
- `@react-three/drei` version: 5.0.0
- "three": "0.128.0",
- "typescript": "~4.3.2",
- `node` version: 12.18.2
- `npm` (or `yarn`) version: 1.22.4

### Problem description:

I got a Typescript error as below after upgraded drei from 2.1.1 to 5.0.0.
Here is the discussion https://github.com/pmndrs/drei/discussions/434

### Relevant code:

Type '{ children: Element; mode: string; position: Vector3; rotation: Euler; onPointerUp: (event: any) => void; }' is missing the following properties from type 'Pick<Props, "id" | "camera" | "quaternion" | "attach"
| "attachArray" | "attachObject" | "args" | "children" | "key" | "onUpdate" | "position" | "up" | "scale" |
"rotation" | ... 89 more ... | "showZ">': camera, size, enabled, space, and 7 more. TS2740

143 |     const transformControl: any = (
144 |       <>
145 | <TransformControls
| ^
146 | mode={mode}
147 | position={getVector3(this.props.instance.position)}
148 | rotation={

### Suggested solution:

I can work around this by either provide all required props or modify https://github.com/pmndrs/drei/blob/master/src/core/TransformControls.tsx#L18 to make them all optional. I will provide a PR to mark most props optional and see your suggestion.

### PR DESCRIPTION
**Pull request by philxia**
### Why

Resolved #444 

### What

Made most props optional for TransformControls, and removed a readonly prop - dragging - based on documentation - https://threejs.org/docs/index.html?q=trans#examples/en/controls/TransformControls

### Checklist

- [x] Ready to be merged

@joshuaellis Please help to review, thanks.

### CODE REVIEW

File: src/core/TransformControls.tsx [hunk 1]
```diff
@@ -17,20 +17,19 @@ declare global {
...
-    rotationSnap: number | null
+    enabled?: boolean
+    axis?: string | null
+    mode?: string
+    translationSnap?: number | null
+    rotationSnap?: number | null
     scaleSnap?: number | null
-    space: string
-    size: number
-    dragging: boolean
```
Comment (philxia) [inline src/core/TransformControls.tsx:28]: Removed this prop as it is a readonly for TransformControls.
https://threejs.org/docs/index.html?q=trans#examples/en/controls/TransformControls
.dragging : Boolean
Whether or not dragging is currently performed. Read-only property.

**Review by joshuaellis — APPROVED** [review]
Thanks for the fix!
