### PR TITLE
fix(MeshTransmissionMaterial): unset USE_ANISOTROPY, add compat alias

### LINKED ISSUE #1482: MeshTransmissionMaterial breaking on three.js r153 when playing with clearcoat or anisotropy
- `three` version: "^0.153.0"
- `@react-three/fiber` version: "^8.12.0"
- `@react-three/drei` version: "^9.58.4"
- `node` version: v16.17.0
- `npm` version: 9.1.3

### Problem description:

The MeshTransmissionMaterial is breaking when using the clearcoat or the anisotropy parameter since the release of the r153 for three.js

Error showing up

It works back on three.js `v0.150.1`

### Relevant code:
```jsx
<Sphere>
        <MeshTransmissionMaterial
          distortionScale={0}
          temporalDistortion={0}
          backside={true}
          thickness={0.1}
          distortion={0}
          chromaticAberration={1}
          roughness={0.6}
          flatShading={true}
          anisotropy={0.05}
          clearcoat={1}
          color={"#ffffff"}
          transmission={0.95}
          envMapIntensity={3}
          ior={1.02}
        />
</Sphere>
 ```

Codesandbox: https://codesandbox.io/p/sandbox/fervent-bird-jofpi1

### PR DESCRIPTION
**Pull request by CodyJasonBennett**
Fixes #1482 where new `USE_ANISOTROPY` chunks break with the custom `anisotropy` prop (now reserved) and adds back the prop removed in 549493df2693828b152b0bc4edf45c3571421146.

### CODE REVIEW

File: src/core/MeshTransmissionMaterial.tsx [hunk 1]
```diff
@@ -119,6 +121,13 @@ class MeshTransmissionMaterialImpl extends THREE.MeshPhysicalMaterial {
         ...this.uniforms,
       }
 
+      // r153+ compat https://github.com/pmndrs/drei/issues/1482
+      shader.defines = { ...shader.defines }
+      Object.defineProperty(shader.defines, 'USE_ANISOTROPY', {
+        get() {},
+        set(_) {},
+      })
+
```
Comment (CodyJasonBennett) [inline src/core/MeshTransmissionMaterial.tsx:130]: This is the "proper" fix, but aliasing `anisotropy` to `anisotropicBlur` on the material also works. Removing this one.
