### PR TITLE
fix: don't import example subpaths for compat

### LINKED ISSUE #1363: Nextjs: Import from drei causes `SyntaxError: Cannot use import statement outside a module`
- `three` version: `0.150.1`
- `@react-three/fiber` version: `8.12.0`
- `@react-three/drei` version: `9.58.4`
- `next` version: `13.2.4`
- `react` version: `18.2.0`
- `node` version: `latest`
- `npm` (or `yarn`) version: `latest`

### Problem description:

It seems that importing anything from drei causes the following error:

```node
SyntaxError: Cannot use import statement outside a module

Call Stack
<unknown>
file:/project/sandbox/node_modules/three-stdlib/utils/BufferGeometryUtils.js (1)
...
```

Here is a small csb showing the issue: https://codesandbox.io/p/sandbox/nervous-andras-l4pkwg

### PR DESCRIPTION
**Pull request by CodyJasonBennett**
Fixes #1363

### CODE REVIEW

**Comment by abernier** [comment]
oopsie 😬

File: src/core/RoundedBox.tsx [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import * as React from 'react'
 import { Mesh, Shape, ExtrudeGeometry } from 'three'
 import { NamedArrayTuple } from '../helpers/ts-utils'
-import { toCreasedNormals } from 'three-stdlib/utils/BufferGeometryUtils'
```
Comment (abernier) [inline src/core/RoundedBox.tsx:4]: @CodyJasonBennett I did this :| but can you explain to me why this was a bad idea? (so I won't make the same error next time) thx

Comment (CodyJasonBennett) [reply src/core/RoundedBox.tsx:4]: Drei doesn't transpile subpaths AFAIK. We can fix this with `package#exports` there but that would be a breaking change. For now, we just import from the root.
